### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by Wiwaltill** [sharecloud/sharecloud#56]
**Fatal error:** Declaration of `Database::query($statement)` must be compatible with `PDO::query(string $query, ?int $fetchMode = null, mixed ...$fetchModeArgs)` in **{ROOT_PATH}/sharecloud/classes/Database.class.php** on line **77**

PHP-Version: 8.0

## Schritte
✅ Datenbank erstellt + verknüpft
✅ Smarty Berechtigung erteilt
❌ Bei Aufruf per Web erscheint Fehler

**Comment by Wiwaltill** [comment]
Unter PHP 7.4:


`Deprecated: The each() function is deprecated. This message will be suppressed on further calls in /homepages/6/d101177282/htdocs/clickandbuilds/TiLL-Test/sharecloud/classes/smarty/sysplugins/smarty_internal_compilebase.php on line 75`

`Warning: Creating default object from empty value in /homepages/6/d101177282/htdocs/clickandbuilds/TiLL-Test/sharecloud/classes/smarty/sysplugins/smarty_internal_compile_block.php on line 84`

Installationsdatei lädt nun. Jedoch ist weiterhin kein Aufruf der Startseite möglich.

**Comment by frostieDE** [comment]
Das Projekt wird nicht mehr aktiv entwickelt - leider kann ich es nicht mehr archivieren, da ich nicht mehr Mitglied der Organisation sharecloud bin - @flashspys könntest du das Projekt archivieren? :)

**Comment by Wiwaltill** [comment]
@frostieDE Schade. Ein echt schönes Projekt!
